### PR TITLE
Support media-attachments, folded sections, non-standard color highlight

### PR DESCRIPTION
**Pull request by Argimko**
Hi @alxnbl, thank you for your great app! I would like to do some commits, the main is: https://github.com/alxnbl/onenote-md-exporter/commit/77ee584f42d6c8d62d812d1cf1912f38bf73bbf6

Please, see PR commit descriptions for more details.

Thank you!

### CODE REVIEW

**Comment by alxnbl** [comment]
Thank you for these commits. At the first glance it looks great!

I will integrate it in the next release of the tool, after having done my regression tests.

**Comment by Argimko** [comment]
@alxnbl, please, when you have time, check the next complex commit.

1. Correctly process folded sections – closes #99
2. Correctly process non-standard text highlight color (Light Green, Teal, Gold, etc.)
3. *(pending)* Convert OneNote Text Tags to #hash-tags with Emoji icons
4. Added `TemporaryNotebook` class to store OneNote pages at temporary section for pre-processing such as: Sections unfold, Convert OneNote tags to hash-tags, Keep checkboxes, etc.
	- If pre-processing **is needed** for some page, it **cloned to temp notebook** with adjusted XML content and then exported to DocX. If page XML **don’t changed** due pre-processing, it exported to DocX from **original place.**
	- Move part of `FillSectionPages()` function and `ProcessPageAttachments()` from `OneNoteExtensions.cs` to `ExportServiceBase.cs/ExportPage()` because we need parsed XML page content for `PageXmlPreProcessing()`
6. Use installed Pandoc when it not found in exporter local folder
7. Refactoring based on Visual Studio suggestions:
	- Apply spell checker suggestions
	- Convert regular class constructors to [primary](https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/instance-constructors#primary-constructors)
	- Made methods `static` where it applicable, across number of classes
8. Refactoring to simplify routing parameters between functions:
	- Use global static class `OneNoteApp` to communicate with OneNote Interop
	- Made class `ConverterService` static
	- Made class `AppSettings` fields static
9. Highlight warning message on Welcome app message about keeping a notebook backups

_I am happy to work with your well-structured code! So I am trying to keep new code clear, and respect your code-style intent._

_Thank you!_

**Comment by alxnbl** [comment]
I started to integrate your change in future 1.5 version of the tool, work in progress. Thanks again for the quality of your contribution!

**Comment by alxnbl** [comment]
@Argimko : regarding "Support of non-standard color highlight : correctly process non-standard text highlight color (Light Green, Teal, Gold, etc.)". I don't really understand in which situation does the fix solve an issue. 
Without your code (in PageXmlPreProcessing method), highlighted text was already translated into ==text== , regardless the highlight color used in OneNote.
Do you have a sample page that illustrate the scenario in which your evolution changes are visible ?

**Comment by Argimko** [comment]
Yes, please check this section [Highlights.zip](https://github.com/user-attachments/files/15846275/Highlights.zip)

**Comment by alxnbl** [comment]
Thanks, indeed I've been able to reproduce. I completed the test notebook with your sample.

**Pull request merged**
