### PR TITLE
some improved

### PR DESCRIPTION
**Pull request by Tlich**
1. Chinese language files are added to make the whole process Chinese

2. The original author designed that all pictures of a notebook are stored in the same folder, and the folder path is: ".. /.. / \ _resource". But this is very inconvenient for me, so I implemented it. Each partition has an independent "_resource" folder to store image files.

3. The modified location is written in my readme file

### CODE REVIEW

**Comment by alxnbl** [comment]
Thanks Tlich for your contribution ! I will review your PR asap.

**Comment by alxnbl** [comment]
Hello Tlich, I review your pull request and thank you for your work. 
Regarding the location of the attachment and pictures, some user can be interested to find all pictures and attachments in a single folder while others (like you) prefer storing them along each md file. So if prefer not accepting the PR because that would only support exporting in a single folder.
If you don't mind, could you reopen a PR that includes only the new translation file. 
Then if you have more time, you can continue your development to change the location of pictures and attachments. What you should do is to add a new parameter "ExportAttachmentsInASingleFolder" of type bool in Infrastructure/AppSettings.cs file, and if it is false then you switch from current behavior to the new behavior your have implemented.
Thanks again

**Comment by alxnbl** [comment]
Finally I will implement the feature in the next release of the app with a dedicated settings. 
It would be great if you can re-open a PR with your translation file.
Thanks

**Comment by alxnbl** [comment]
Hi @Tlich , I have implemented the parameter to choose the location of the images/attachments folder, its part of 1.1 release.  Just waiting you new PR to integrate your translations in the next release.

**Comment by Tlich** [comment]
ok, I will give you a new PR as soon as possible which only have translations. And I also will add Chinese in Infrastructure/AppSettings.cs file

**Pull request closed without merging**
